### PR TITLE
Change MA recipe for GC titanium

### PR DESCRIPTION
**Pull request by burgerhex**
The current Mystical Agriculture recipe for Galacticraft titanium is the same as the recipe for Alchemistry titanium, so the former is uncraftable; this change removes that collision (by slightly nerfing the recipe).

### CODE REVIEW

**Comment by WaitingIdly** [comment]
while this change does fix the problem stated, the actual problem is alchemistry titanium being obtainable. do you want to to make that change yourself (fixing all locations in which alchemistry titanium is obtainable)?

**Comment by burgerhex** [comment]
These are all the recipes I could find for alchemistry titanium (except for the chemical combiner recipe which should probably stay)

**Comment by WaitingIdly** [comment]
chemical combiner should also be changed. and its should just be "remove", it should be "replace with the correct titanium"

**Comment by burgerhex** [comment]
Combiner removed and induction smelter replaced. Casting and chemical combiner already have the correct recipes (i.e. there were collisions) so I don't think we explicitly need to add them again

**Comment by WaitingIdly** [comment]
hadnt noticed until now: its not `<alchemistry:element:22>`, its `<alchemistry:ingot:22>`. loaded this up in-game and was wondering why the recipes were still there.

**Comment by burgerhex** [comment]
Should be fixed now

**Review by WaitingIdly — APPROVED** [review]

**Comment by WaitingIdly** [comment]
splendid, thanks

**Pull request merged**
