### PR TITLE
Resprites the Angelic Silicon Crystal Mix and its block

### PR DESCRIPTION
**Pull request by AdipemDragon**
image

Just about what it says on the tin, really. I mostly just didn't want to look at that 40x40 sprite being resized automatically by JEI.

### CODE REVIEW

**Comment by KleinGrrmpf** [comment]
I love the item texture! Could you apply the block texture to the block model and have that displayed with your texture as a side texture for the item too?

**Comment by AdipemDragon** [comment]
I'd either have to edit it manually with my drawing program(the block'll look blurry) or to get help from someone who knows what they're doing to actually "import" it in the game to take actual screenshots, gimme a minute eitherway

**Comment by KleinGrrmpf** [comment]
[angelic_silicon_crystal_block.zip](https://github.com/Divine-Journey-2/Divine-Journey-2/files/11289182/angelic_silicon_crystal_block.zip)

Unzip this and add the .json file into resources/contenttweaker/model/block and see if that works. This JSON file assumes that you replaced the old angelic_silicon_crystal_block texture file with your current one (so that their paths are exactly the same)

**Comment by AdipemDragon** [comment]
image

**Comment by KleinGrrmpf** [comment]
Awesome!

**Comment by WaitingIdly** [comment]
thanks for the new textures, sorry for the long delay

**Comment by AdipemDragon** [comment]
Finally, time for more sprites

**Pull request merged**
