### PR TITLE
DJ2Addons Beta Update

### PR DESCRIPTION
**Pull request by ByThePowerOfScience**
> ### [DJ2Addons 1.2.2 - BETA](https://legacy.curseforge.com/minecraft/mc-mods/divine-journey-2-addons/files/4765604)
> 
> Structure:
>  - Moved coremod to its own mod instead of having a mod/coremod hybrid.
>  - Changed "value" classes to formal API classes for use by other modmakers.
> 
> Optimizations:
>  - Industrial Foregoing - Plant Interactor: Moved "canBlockBeBroken" check to after it determines if the block is a crop.
>  - Aether: Fixed "Accessories" handler lagging the server to a halt.
> 
> Patches:
>  - PackagedAuto: Now includes NBT data properly in recipes.
> 
> APIs:
>  - Mystical Agriculture: Add Seed Reprocessor recipes.
>  - Thaumcraft: Add infusion stabilizers using extremely jank config.
>  - Botania: Add brew recipes that only work for a specific output container. (e.g. A vial of a potion that requires nether wart and beef, but a tainted blood pendant of the same potion that requires nether wart, beef, and a nether star.)
>  - Bewitchment: Remove altar upgrades.
>  - Extra Utilities 2: Disallow certain biomes from being used in the Quantum Quarry.
> 
> Commands: (see docs on GitHub)
>  - Ability to dump a tile's state to the log, and also to stop that dump if it goes a bit too deep.
> 
> Tweaks:
> Extra Utilities 2 - Mechanical User:
>  - Now gives a comparator output based on its inventory. (probably not necessary actually, will remove in actual release)
>  - User can now act with the placer's Thaumcraft research. (for use on Infusion Altars)

Actual DJ2 changes in this PR:

- Added recipe for Enderium using blocks of ender pearls
- Increased water bottle and potion stack size to 16
- Fixed resource capitalization errors in puzzle pieces
- Blacklisted Atum biomes from being used in the quantum quarry to fix server crashes.
- Changed the Warp Ward brew to only have the more expensive recipe used for the Tainted Blood Pendant, with the consumable versions still using the original recipe and duration.

### CODE REVIEW

**Review by WaitingIdly — CHANGES_REQUESTED** [review]
both `Botania.zs` (no method available) and `ExtraUtilities2.zs` (NPE) scripts error and cannot be run.
while i understand the changes for textures, potions, and enderium, those should be done in separate PRs

**Comment by ByThePowerOfScience** [comment]
> while i understand the changes for textures, potions, and enderium, those should be done in separate PRs.
For sure! I didn't mean to include them actually; I just realized I had committed the DJ2A updates to the same fork when I made the pull so I just ran with it. 😅 
I'll see if I can remove the commits from the branch without messing everything up.

**Comment by KleinGrrmpf** [comment]
I'd like to see comparator outputs by the mechanical user, so it wouldn't be unnecessary imo

**Comment by ByThePowerOfScience** [comment]
> I'd like to see comparator outputs by the mechanical user, so it wouldn't be unnecessary imo

The Inventory Reader works on them, so it isn't a strictly-necessary feature and I'd like to avoid messing with things that I don't have to.

**Pull request closed without merging**
